//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core.Transformation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransformationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransformationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.Transformation.TransformationResources", typeof(TransformationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if the transformed page is the web&apos;s home page.
        /// </summary>
        internal static string Debug_TransformCheckIfPageIsHomePage {
            get {
                return ResourceManager.GetString("Debug_TransformCheckIfPageIsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page transformation for targeting non-modern sites is currently not supported.
        /// </summary>
        internal static string Error_CrossSiteTransferTargetsNonModernSite {
            get {
                return ResourceManager.GetString("Error_CrossSiteTransferTargetsNonModernSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing UserMappingProvider in current services configuration.
        /// </summary>
        internal static string Error_MissingUserMappingProvider {
            get {
                return ResourceManager.GetString("Error_MissingUserMappingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target page &apos;{0}&apos; already exists and overwrite is not configured.
        /// </summary>
        internal static string Error_PageNotOverwriteIfExists {
            get {
                return ResourceManager.GetString("Error_PageNotOverwriteIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page &apos;{0}&apos; already exists in target location.
        /// </summary>
        internal static string Info_PageAlreadyExistsInTargetLocation {
            get {
                return ResourceManager.GetString("Info_PageAlreadyExistsInTargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url:.
        /// </summary>
        internal static string Info_TransformArticleHeaderImageUrl {
            get {
                return ResourceManager.GetString("Info_TransformArticleHeaderImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Header Set to Custom. Using page header settings:.
        /// </summary>
        internal static string Info_TransformArticleSetHeaderToCustom {
            get {
                return ResourceManager.GetString("Info_TransformArticleSetHeaderToCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Header Set to Default. Using page header default settings.
        /// </summary>
        internal static string Info_TransformArticleSetHeaderToDefault {
            get {
                return ResourceManager.GetString("Info_TransformArticleSetHeaderToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Header Set to None. Removing the page header.
        /// </summary>
        internal static string Info_TransformArticleSetHeaderToNone {
            get {
                return ResourceManager.GetString("Info_TransformArticleSetHeaderToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting page author in page header.
        /// </summary>
        internal static string Info_TransformArticleSetHeaderToNoneWithAuthor {
            get {
                return ResourceManager.GetString("Info_TransformArticleSetHeaderToNoneWithAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforming source page as Article page.
        /// </summary>
        internal static string Info_TransformSourcePageAsArticlePage {
            get {
                return ResourceManager.GetString("Info_TransformSourcePageAsArticlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a stock homepage layout as the new homepage - not transforming page.
        /// </summary>
        internal static string Info_TransformSourcePageHomePageUsingStock {
            get {
                return ResourceManager.GetString("Info_TransformSourcePageHomePageUsingStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page author header could not be set. Author &apos;{0}&apos; could not be resolved.
        /// </summary>
        internal static string Warning_PageHeaderAuthorNotSet {
            get {
                return ResourceManager.GetString("Warning_PageHeaderAuthorNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page author header could not be set. Error: &apos;{0}&apos;.
        /// </summary>
        internal static string Warning_PageHeaderAuthorNotSetGenericError {
            get {
                return ResourceManager.GetString("Warning_PageHeaderAuthorNotSetGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting a page as news requires the page to be published. Turning on the PublishCreatedPage flag.
        /// </summary>
        internal static string Warning_PostingAPageAsNewsRequiresPagePublishing {
            get {
                return ResourceManager.GetString("Warning_PostingAPageAsNewsRequiresPagePublishing", resourceCulture);
            }
        }
    }
}
