namespace PnP.Core.Model.SharePoint
{
    /// <summary>
    /// Represents the unique sequential location of a change within the change log.
    /// </summary>
    [ConcreteType(typeof(ChangeToken))]
    public interface IChangeToken
    {
        /// <summary>
        /// Gets or sets a string value that contains the serialized representation of the change token generated by the protocol server.
        /// </summary>
        public string StringValue { get; }
    }
}