//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PnPCoreAdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PnPCoreAdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.Admin.PnPCoreAdminResources", typeof(PnPCoreAdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site creation for site {0} did not succeed. Returned siteStatus = {1}.
        /// </summary>
        internal static string Exception_SiteCreation {
            get {
                return ResourceManager.GetString("Exception_SiteCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for the status of site creation for site {0} did fail. Last returned siteStatus = {1}.
        /// </summary>
        internal static string Exception_SiteCreationStatusCheck {
            get {
                return ResourceManager.GetString("Exception_SiteCreationStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanity urls are currently not handled..
        /// </summary>
        internal static string Exception_VanityUrl {
            get {
                return ResourceManager.GetString("Exception_VanityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following exception was eaten while getting the tenant admins: {0}.
        /// </summary>
        internal static string Log_Information_ExceptionWhileGettingSharePointAdmins {
            get {
                return ResourceManager.GetString("Log_Information_ExceptionWhileGettingSharePointAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following exception was eaten while getting the status of the site creation of {0} : {1}.
        /// </summary>
        internal static string Log_Warning_ExceptionWhileGettingSiteStatus {
            get {
                return ResourceManager.GetString("Log_Warning_ExceptionWhileGettingSiteStatus", resourceCulture);
            }
        }
    }
}
