namespace PnP.Core.Model.SharePoint
{
    /// <summary>
    /// Represents a change token that is usable in <seealso cref="ChangeQueryOptions"/>.
    /// </summary>
    /// <seealso cref="IChangeToken" />
    public class ChangeTokenOptions : IChangeToken
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeTokenOptions"/> class.
        /// </summary>
        public ChangeTokenOptions()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeTokenOptions"/> class.
        /// </summary>
        /// <param name="stringValue">The string value.</param>
        public ChangeTokenOptions(string stringValue)
        {
            StringValue = stringValue;
        }

        /// <summary>
        /// Gets or sets a string value that contains the serialized representation of the change token generated by the protocol server.
        /// </summary>
        public string StringValue { get; set; }

        /// <summary>
        /// Converts to string.
        /// </summary>
        /// <returns>
        /// A <see cref="string" /> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return StringValue;
        }
    }
}
