namespace PnP.Core.Provisioning.Model.Configuration
{
    public enum ConfigurationHandler
    {
        AuditSettings,
        ComposedLook,
        CustomActions,
        ExtensibilityProviders,
        Features,
        Fields,
        Files,
        Lists,
        Pages,
        Publishing,
        RegionalSettings,
        SearchSettings,
        SitePolicy,
        SupportedUILanguages,
        Taxonomy,
        Workflows,
        SiteSecurity,
        ContentTypes,
        PropertyBagEntries,
        WebSettings,
        Navigation,
        ImageRenditions,
        ApplicationLifecycleManagement,
        Tenant,
        WebApiPermissions,
        SiteHeader,
        SiteFooter,
        Theme,
        SiteSettings,
        SyntexModels
    }
}
