//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core.Provisioning {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PnPCoreProvisioningResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PnPCoreProvisioningResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.Provisioning.PnPCoreProvisioningResources", typeof(PnPCoreProvisioningResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graph call returned the following error: {0}..
        /// </summary>
        internal static string GraphExtensions_ErrorOccured {
            get {
                return ResourceManager.GetString("GraphExtensions_ErrorOccured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating property {0}.
        /// </summary>
        internal static string PnPMonitoredScopeExtensions_LogPropertyUpdate_Updating_property__0_ {
            get {
                return ResourceManager.GetString("PnPMonitoredScopeExtensions_LogPropertyUpdate_Updating_property__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The source site from which the template was generated had a base template ID value of {0}, while the current target site has a base template ID value of {1}. This could cause potential issues while ap [rest of string was truncated]&amp;quot;;.
        /// </summary>
        internal static string Provisioning_Asymmetric_Base_Templates {
            get {
                return ResourceManager.GetString("Provisioning_Asymmetric_Base_Templates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from folder {1}. Error = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileDeleteFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from folder {1} because it was not available.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileDeleteNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileDeleteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted from folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileDeleted {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in directory {1}. Exception = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} retrieved from folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileRetrieved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileRetrieved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not saved to folder {1}. Error = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileSaveFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} saved to folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_FileSystem_FileSaved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_FileSystem_FileSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from folder {1}. Error = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileDeleteFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from folder {1} because it was not available.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileDeleteNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileDeleteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted from folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileDeleted {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in directory {1}. Exception = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} retrieved from folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileRetrieved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileRetrieved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not saved to folder {1}. Error = {2}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileSaveFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} saved to folder {1}.
        /// </summary>
        internal static string Provisioning_Connectors_OpenXML_FileSaved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_OpenXML_FileSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from site {1}, library {2}. Error = {3}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileDeleteFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not deleted from site {1}, library {2} because it was not available.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileDeleteNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileDeleteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted from site {1}, library {2}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileDeleted {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in site {1}, library  {2}. Exception = {3}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileNotFound {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0}  found in site {1}, library  {2}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileRetrieved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileRetrieved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} was not saved to site {1}, library {2}. Error = {3}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileSaveFailed {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File {0} saved to site {1}, library {2}.
        /// </summary>
        internal static string Provisioning_Connectors_SharePoint_FileSaved {
            get {
                return ResourceManager.GetString("Provisioning_Connectors_SharePoint_FileSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The extensibility handler does not implement a supported extensibility handler interface. Check if the extensibility handler references the same version of OfficeDevPnP currently in use (Version {0}). [rest of string was truncated]&amp;quot;;.
        /// </summary>
        internal static string Provisioning_Extensibility_Invalid_Handler_Implementation {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Invalid_Handler_Implementation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning extensibility pipeline preparing to invoke, Assembly: {0}. Type {1}.
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_BeforeInvocation {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_BeforeInvocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ClientContext is NULL. Unable to Invoke Extensibility Pipeline..
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_ClientCtxNull {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_ClientCtxNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an exception invoking the custom extensibility provider. Assembly: {0}, Type: {1}. Exception {2}.
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_Exception {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_Exception", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider.Assembly missing value. Unable to Invoke Extensibility Pipeline..
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_Missing_AssemblyName {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_Missing_AssemblyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider.Type missing value. Unable to Invoke Extensibility Pipeline..
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_Missing_TypeName {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_Missing_TypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning extensibility pipline invocation successful, Assembly {0}, Type {1}.
        /// </summary>
        internal static string Provisioning_Extensibility_Pipeline_Success {
            get {
                return ResourceManager.GetString("Provisioning_Extensibility_Pipeline_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Navigation translation needed since web is single language.
        /// </summary>
        internal static string Provisioning_Extensions_NavigationLocalization_NoMUI_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_NavigationLocalization_NoMUI_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping navigation localization because we're running under a user context who has a preferred language set in it's profile. This setup will not allow to add the needed localized string versions..
        /// </summary>
        internal static string Provisioning_Extensions_NavigationLocalization_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_NavigationLocalization_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translation for default language of site is missing.
        /// </summary>
        internal static string Provisioning_Extensions_ViewLocalization_DefaultLngMissing_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_ViewLocalization_DefaultLngMissing_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Viewtranslation needed since web is single language.
        /// </summary>
        internal static string Provisioning_Extensions_ViewLocalization_NoMUI_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_ViewLocalization_NoMUI_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping view localization because we're running under a user context who has a preferred language set in it's profile. This setup will not allow to add the needed localized string versions..
        /// </summary>
        internal static string Provisioning_Extensions_ViewLocalization_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_ViewLocalization_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No WebPart translation needed since web is single language.
        /// </summary>
        internal static string Provisioning_Extensions_WebPartLocalization_NoMUI_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_WebPartLocalization_NoMUI_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping web part localization because we're running under a user context who has a preferred language set in it's profile. This setup will not allow to add the needed localized string versions..
        /// </summary>
        internal static string Provisioning_Extensions_WebPartLocalization_Skip {
            get {
                return ResourceManager.GetString("Provisioning_Extensions_WebPartLocalization_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Provisioning Template URI {0} is not valid..
        /// </summary>
        internal static string Provisioning_Formatter_Invalid_Template_URI {
            get {
                return ResourceManager.GetString("Provisioning_Formatter_Invalid_Template_URI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_AAD_User_AlreadyExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_AAD_User_AlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning a user failed..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_AAD_User_ProvisioningError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_AAD_User_ProvisioningError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audit log trimming retention is not set because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Audit_SkipAuditLogTrimmingRetention {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Audit_SkipAuditLogTrimmingRetention", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This page is an uncustomized, default home page, so no need to extract it..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ClientSidePageContents_DefaultHomePage {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ClientSidePageContents_DefaultHomePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error during automatic client side page connected file export: {0}..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ClientSidePageContents_ErrorDuringFileExport {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ClientSidePageContents_ErrorDuringFileExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This page is not a valid client side page and can't be extracted. Underlying error = {0}..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ClientSidePageContents_NoValidPage {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ClientSidePageContents_NoValidPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find the control with either ID = {0} or Name = {1} to install. Did you install your client side web part to this site?.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ClientSidePages_BaseControlNotFound {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ClientSidePages_BaseControlNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page with name {0} did already exist and the overwrite flag was not set, so nothing happened.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ClientSidePages_NoOverWrite {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ClientSidePages_NoOverWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading asset: {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_DownLoadFile_Downloading_asset___0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_DownLoadFile_Downloading_asset___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Composed Look Information in Property Bag failed to deserialize. Falling back to detection of current composed look.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_ComposedLookInfoFailedToDeserialize {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_ComposedLookInfoFailedToDeserialize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating SharePointConnector.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Creating_SharePointConnector {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Creating_SharePointConnector", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieving current composed look.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Retrieving_current_composed_look {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Retrieving_current_composed_look", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using Composed Look Information from Property Bag.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Using_ComposedLookInfoFromPropertyBag {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_ExtractObjects_Using_ComposedLookInfoFromPropertyBag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping composed look handling because the site is marked as 'nosite'..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ComposedLooks_NoSiteCheck {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ComposedLooks_NoSiteCheck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding content type to template: {0} - {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Adding_content_type_to_template___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Adding_content_type_to_template___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding field {0} to content type.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Adding_field__0__to_content_type {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Adding_field__0__to_content_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating new Content Type: {0} - {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Creating_new_Content_Type___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Creating_new_Content_Type___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add '{1}' as DocumentTemplate to ContentType '{0}'.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_ErrorDocumentTemplate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_ErrorDocumentTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to extract DefaultDocument '{0}' from DocumentSet.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_ErrorExtractDocumentSetTemplate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_ErrorExtractDocumentSetTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to extract DocumentTemplate '{1}' from ContentType '{0}'.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_ErrorSaveDocumentTemplateToConnector {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_ErrorSaveDocumentTemplateToConnector", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field {0} exists in content type.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Field__0__exists_in_content_type {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Field__0__exists_in_content_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Content Type {0} with ID {1} cannot be transformed into a DocumentSet.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_InvalidDocumentSet_Update_Request {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_InvalidDocumentSet_Update_Request", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recreating existing Content Type: {0} - {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Recreating_existing_Content_Type___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Recreating_existing_Content_Type___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping custom form URLs for contenttype '{0}' because we can't upload them on 'noscript' sites..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_SkipCustomFormUrls {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_SkipCustomFormUrls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping adding default documents to document set '{0}' because this is not supported on 'noscript' sites..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_SkipDocumentSetDefaultDocuments {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_SkipDocumentSetDefaultDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping uploading template as set in DocumentTemplate for ContentType '{0}' because we can't upload them on 'noscript' sites..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_SkipDocumentTemplate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_SkipDocumentTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Existing content type with Id {0} and name {1} will not be updated because it's marked as sealed or read only and the template is not changing the value..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Updating_existing_Content_Type_SealedOrReadOnly {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Updating_existing_Content_Type_SealedOrReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating existing Content Type: {0} - {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ContentTypes_Updating_existing_Content_Type___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ContentTypes_Updating_existing_Content_Type___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding custom action '{0}' to scope Site.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Adding_custom_action___0___to_scope_Site {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Adding_custom_action___0___to_scope_Site", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding custom action '{0}' to scope Web.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Adding_custom_action___0___to_scope_Web {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Adding_custom_action___0___to_scope_Web", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding site scoped custom action '{0}' to template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Adding_site_scoped_custom_action___0___to_template {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Adding_site_scoped_custom_action___0___to_template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding web scoped custom action '{0}' to template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Adding_web_scoped_custom_action___0___to_template {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Adding_web_scoped_custom_action___0___to_template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removing site scoped custom action '{0}' from template because already available in base template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Removing_site_scoped_custom_action___0___from_template_because_already_available_in_base_template {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Removing_site_scoped_custom_action___0___from_template_because_already_available_in_base_template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removing web scoped custom action '{0}' from template because already available in base template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_Removing_web_scoped_custom_action___0___from_template_because_already_available_in_base_template {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_Removing_web_scoped_custom_action___0___from_template_because_already_available_in_base_template", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom action '{0}' was not added/updated because the site was configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_CustomActions_SkippingAddUpdateDueToNoScript {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_CustomActions_SkippingAddUpdateDueToNoScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calling extensibility callout {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ExtensibilityProviders_Calling_extensibility_callout__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ExtensibilityProviders_Calling_extensibility_callout__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calling extensibility tokenprovider callout {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ExtensibilityProviders_Calling_tokenprovider_extensibility_callout__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ExtensibilityProviders_Calling_tokenprovider_extensibility_callout__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extensibility callout failed: {0} : {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ExtensibilityProviders_callout_failed___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ExtensibilityProviders_callout_failed___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extensibility tokenprovider callout failed: {0} : {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ExtensibilityProviders_tokenprovider_callout_failed___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ExtensibilityProviders_tokenprovider_callout_failed___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Extraction {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Extraction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activating {0} scoped feature {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Features_Activating__0__scoped_feature__1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Features_Activating__0__scoped_feature__1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0} scoped feature {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Features_Deactivating__0__scoped_feature__1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Features_Deactivating__0__scoped_feature__1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding field {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Adding_field__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Adding_field__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding field {0} to site.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Adding_field__0__to_site {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Adding_field__0__to_site", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Context web is subweb, skipping site columns.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Context_web_is_subweb__skipping_site_columns {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Context_web_is_subweb__skipping_site_columns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field {0} ({1}) exists but is of different type. Skipping field..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Field__0____1___exists_but_is_of_different_type__Skipping_field_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Field__0____1___exists_but_is_of_different_type__Skipping_field_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating field {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Updating_field__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Updating_field__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating field {0} in site.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Updating_field__0__in_site {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Updating_field__0__in_site", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating field {0} received a timeout when pushing changes to lists.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Fields_Updating_field__0__timeout {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Fields_Updating_field__0__timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding webpart '{0}' to page.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Files_Adding_webpart___0___to_page {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Files_Adding_webpart___0___to_page", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping upload of file '{0}' to '{1}'..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Files_SkipFileUpload {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Files_SkipFileUpload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploading and overwriting existing file {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Files_Uploading_and_overwriting_existing_file__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Files_Uploading_and_overwriting_existing_file__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploading file {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Files_Uploading_file__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Files_Uploading_file__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating list item {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_list_item__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_list_item__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This row already exists and will be skipped because the IgnoreDuplicateDataRowErrors flag is set to true..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_duplicate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating listitem failed: {0} : {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_failed___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_failed___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating list items in document libraries is not supported. Please remove DataRow elements for library '{0}'..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_notsupported_0 {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstancesDataRows_Creating_listitem_notsupported_0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing data rows for {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstancesDataRows_Processing_data_rows_for__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstancesDataRows_Processing_data_rows_for__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added property bag entry {0} to list {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Added_PropertyBagEntry__0__To_List__1 {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Added_PropertyBagEntry__0__To_List__1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding list: {0} - {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Adding_list___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Adding_list___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating field {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_field__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_field__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating field {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_field__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_field__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating list {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_list__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_list__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating list {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_list__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_list__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating view {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_view__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_view__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating view failed: {0} : {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Creating_view_failed___0_____1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Creating_view_failed___0_____1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DraftVersionVisibility not applied to list {0} because EnableModeration is not set to true.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_DraftVersionVisibility_not_applied_to_list_0_because_EnableModeration_is_not_set_to_true {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_DraftVersionVisibility_not_applied_to_list_0_because_EnableModeration_is_not_set_to_true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating list {0} with FieldRef {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_FieldRef_Updating_list__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_FieldRef_Updating_list__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field {0} ({1}) exists in list {2} ({3}) but is of different type. Skipping field..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Field__0____1___exists_in_list__2____3___but_is_of_different_type__Skipping_field_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Field__0____1___exists_in_list__2____3___but_is_of_different_type__Skipping_field_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field schema has no ID attribute: {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Field_schema_has_no_ID_attribute___0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Field_schema_has_no_ID_attribute___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder '{0}' already exists in parent folder '{1}'..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_FolderAlreadyExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_FolderAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID for field is not a valid Guid: {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_ID_for_field_is_not_a_valid_Guid___0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_ID_for_field_is_not_a_valid_Guid___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The List {0} references site field {1} ({2}) which could not be found in the site. Use of the site field has been aborted..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_InvalidFieldReference {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_InvalidFieldReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List {0} ({1}, {2}) exists but is of a different type. Skipping list..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_List__0____1____2___exists_but_is_of_a_different_type__Skipping_list_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_List__0____1____2___exists_but_is_of_a_different_type__Skipping_list_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ListInstance {0} is a Style Library of a site with NoScript enabled and will be skipped.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_List__0__is_Style_Library_of_NoScript_will_Skip {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_List__0__is_Style_Library_of_NoScript_will_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip adding/updating custom actions because the site has "noscript" enabled..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_SkipAddingOrUpdatingCustomActions {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_SkipAddingOrUpdatingCustomActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Webhook {0} has been expired and will be skipped during creation/update of list {1}..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_SkipExpiredWebHook {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_SkipExpiredWebHook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating field {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Updating_field__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Updating_field__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating field {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Updating_field__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Updating_field__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating list {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Updating_list__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Updating_list__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating list {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Updating_list__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Updating_list__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error during webhook add/update: {0}..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_ListInstances_Webhook_Error {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_ListInstances_Webhook_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Context web does not have the publishing features enabled, skipping navigation settings.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_Context_web_is_not_publishing {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_Context_web_is_not_publishing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning of the navigation node failed : {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_Link_Provisioning_Failed {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_Link_Provisioning_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning of the navigation node failed, retrying for : {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_Link_Provisioning_Failed_Retry {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_Link_Provisioning_Failed_Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing Current Managed Navigation settings in the current template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_missing_current_managed_navigation {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_missing_current_managed_navigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing Current Structural Navigation settings in the current template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_missing_current_structural_navigation {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_missing_current_structural_navigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing Global Managed Navigation settings in the current template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_missing_global_managed_navigation {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_missing_global_managed_navigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing Global Structural Navigation settings in the current template.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Navigation_missing_global_structural_navigation {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Navigation_missing_global_structural_navigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating new page {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Pages_Creating_new_page__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Pages_Creating_new_page__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating new page {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Pages_Creating_new_page__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Pages_Creating_new_page__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overwriting existing page {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Pages_Overwriting_existing_page__0_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Pages_Overwriting_existing_page__0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overwriting existing page {0} failed: {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Pages_Overwriting_existing_page__0__failed___1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Pages_Overwriting_existing_page__0__failed___1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipped adding web parts to page '{0}' because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Pages_SkipAddingWebParts {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Pages_SkipAddingWebParts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating new propertybag entry {0} with value {1}{2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_PropertyBagEntries_Creating_new_propertybag_entry__0__with_value__1__2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_PropertyBagEntries_Creating_new_propertybag_entry__0__with_value__1__2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overwriting existing propertybag entry {0} with value {1}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_PropertyBagEntries_Overwriting_existing_propertybag_entry__0__with_value__1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_PropertyBagEntries_Overwriting_existing_propertybag_entry__0__with_value__1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Provisioning {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Provisioning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip provisioning of publishing settings because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Publishing_SkipProvisioning {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Publishing_SkipProvisioning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieve Template Info.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_RetrieveTemplateInfo {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_RetrieveTemplateInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site policy '{0}' applied to site.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_SitePolicy_PolicyAdded {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_SitePolicy_PolicyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site policy '{0}' not found.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_SitePolicy_PolicyNotFound {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_SitePolicy_PolicyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add users failed for group '{0}': {1} : {2}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_SiteSecurity_Add_users_failed_for_group___0_____1_____2_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_SiteSecurity_Add_users_failed_for_group___0_____1_____2_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Context web is subweb, skipping site security provisioning.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_SiteSecurity_Context_web_is_subweb__skipping_site_security_provisioning {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_SiteSecurity_Context_web_is_subweb__skipping_site_security_provisioning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning a team based on a team template failed. Ensure that the JSON template markup is valid and contains all the required properties. {0}.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_TeamTemplate_ProvisioningError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_TeamTemplate_ProvisioningError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add member to team..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_AddingMemberError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_AddingMemberError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add owner to team..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_AddingOwnerError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_AddingOwnerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team already exists.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_AlreadyExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_AlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot register App for Team..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_AppProvisioningError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_AppProvisioningError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot send a message to the target Channel..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_CannotSendMessage {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_CannotSendMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel already exists..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_ChannelAlreadyExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_ChannelAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exception while archiving/unarchiving Team with ID {0}. Details: {1}..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_FailedArchiveUnarchive {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_FailedArchiveUnarchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get team information after provisioning..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_FetchingError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_FetchingError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get user by upn information..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_FetchingUserError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_FetchingUserError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group with ID {0} does not exist..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_GroupDoesNotExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_GroupDoesNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to list team members..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_ListingMembersError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_ListingMembersError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to list team owners..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_ListingOwnersError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_ListingOwnersError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provisioning a team failed..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_ProvisioningError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_ProvisioningError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to remove member from team..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_RemovingMemberError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_RemovingMemberError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to remove owner from team..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_RemovingOwnerError {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_RemovingOwnerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab already exists..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_Teams_Team_TabAlreadyExists {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_Teams_Team_TabAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping label {0}, label is to set to default for language {1} while the default termstore language is also {1} or language {1} is not defined for the termstore.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_TermGroups_Skipping_label__0___label_is_to_set_to_default_for_language__1__while_the_default_termstore_language_is_also__1_ {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_TermGroups_Skipping_label__0___label_is_to_set_to_default_for_language__1__while_the_default_termstore_language_is_also__1_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Managed Metadata Service is not properly configured. Please set a default storage location for Keywords and for column specific term sets. The TermGroups handler execution will be skipped!.
        /// </summary>
        internal static string Provisioning_ObjectHandlers_TermGroups_Wrong_Configuration {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_TermGroups_Wrong_Configuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping custom master page update because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_WebSettings_SkipCustomMasterPageUpdate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_WebSettings_SkipCustomMasterPageUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping master page update because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_WebSettings_SkipMasterPageUpdate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_WebSettings_SkipMasterPageUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping NoCrawl update because the site is configured for noscript..
        /// </summary>
        internal static string Provisioning_ObjectHandlers_WebSettings_SkipNoCrawlUpdate {
            get {
                return ResourceManager.GetString("Provisioning_ObjectHandlers_WebSettings_SkipNoCrawlUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot process XML file {0}..
        /// </summary>
        internal static string Provisioning_Providers_XML_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Provisioning_Providers_XML_InvalidFileFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OverwriteSystemPropertyBagValues is to true.
        /// </summary>
        internal static string SiteToTemplateConversion_ApplyRemoteTemplate_OverwriteSystemPropertyBagValues_is_to_true {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_ApplyRemoteTemplate_OverwriteSystemPropertyBagValues_is_to_true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base template available: {0}.
        /// </summary>
        internal static string SiteToTemplateConversion_Base_template_available___0_ {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_Base_template_available___0_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IncludeAllTermGroups is set to true.
        /// </summary>
        internal static string SiteToTemplateConversion_IncludeAllTermGroups_is_set_to_true {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_IncludeAllTermGroups_is_set_to_true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IncludeSiteCollectionTermGroup is set to true.
        /// </summary>
        internal static string SiteToTemplateConversion_IncludeSiteCollectionTermGroup_is_set_to_true {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_IncludeSiteCollectionTermGroup_is_set_to_true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MessagesDelegate registered.
        /// </summary>
        internal static string SiteToTemplateConversion_MessagesDelegate_registered {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_MessagesDelegate_registered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PersistBrandingFiles is set to true.
        /// </summary>
        internal static string SiteToTemplateConversion_PersistBrandingFiles_is_set_to_true {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_PersistBrandingFiles_is_set_to_true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProgressDelegate registered.
        /// </summary>
        internal static string SiteToTemplateConversion_ProgressDelegate_registered {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_ProgressDelegate_registered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scope of template does not match target.
        /// </summary>
        internal static string SiteToTemplateConversion_ScopeOfTemplateDoesNotMatchTarget {
            get {
                return ResourceManager.GetString("SiteToTemplateConversion_ScopeOfTemplateDoesNotMatchTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login context does not have access to the TermGroup. If using app context, add app@sharepoint to the term group access list..
        /// </summary>
        internal static string TermGroup_No_Access {
            get {
                return ResourceManager.GetString("TermGroup_No_Access", resourceCulture);
            }
        }
    }
}
