//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PnPCoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PnPCoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.PnPCoreResources", typeof(PnPCoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expression is not valid.
        /// </summary>
        internal static string Exception_ArgumentExpressionNotValid {
            get {
                return ResourceManager.GetString("Exception_ArgumentExpressionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be 0.
        /// </summary>
        internal static string Exception_CannotBeZero {
            get {
                return ResourceManager.GetString("Exception_CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you load this collection once before calling GetAllPages or GetNextPage.
        /// </summary>
        internal static string Exception_CollectionNotLoaded {
            get {
                return ResourceManager.GetString("Exception_CollectionNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GraphAlwaysUseBeta is set to true, you can&apos;t turn off the &apos;on-demand&apos; beta support. First set GraphAlwaysUseBeta to false before turning of GraphCanUseBeta.
        /// </summary>
        internal static string Exception_ConfigurationError_CannotSetCanUseBeta {
            get {
                return ResourceManager.GetString("Exception_ConfigurationError_CannotSetCanUseBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration name &apos;{0}&apos; for PnPContext creation.
        /// </summary>
        internal static string Exception_ConfigurationError_InvalidPnPContextConfigurationName {
            get {
                return ResourceManager.GetString("Exception_ConfigurationError_InvalidPnPContextConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature was already activated.
        /// </summary>
        internal static string Exception_Feature_AlreadyActivated {
            get {
                return ResourceManager.GetString("Exception_Feature_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature was not activated, nothing to deactive.
        /// </summary>
        internal static string Exception_Feature_CannotDeactivateNotActive {
            get {
                return ResourceManager.GetString("Exception_Feature_CannotDeactivateNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding this entity requires the use of the Graph beta endpoint.
        /// </summary>
        internal static string Exception_GraphBetaNotAllowed {
            get {
                return ResourceManager.GetString("Exception_GraphBetaNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model instance was deleted, you can&apos;t use it anymore.
        /// </summary>
        internal static string Exception_InstanceWasDeleted {
            get {
                return ResourceManager.GetString("Exception_InstanceWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        internal static string Exception_Invalid_FieldType {
            get {
                return ResourceManager.GetString("Exception_Invalid_FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid for field type {1}.
        /// </summary>
        internal static string Exception_Invalid_ForFieldType {
            get {
                return ResourceManager.GetString("Exception_Invalid_ForFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified field parameters are not valid for lookup type fields.
        /// </summary>
        internal static string Exception_Invalid_LookupFields {
            get {
                return ResourceManager.GetString("Exception_Invalid_LookupFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments number.
        /// </summary>
        internal static string Exception_InvalidArgumentsNumber {
            get {
                return ResourceManager.GetString("Exception_InvalidArgumentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain model configuration for entity {0}.
        /// </summary>
        internal static string Exception_InvalidDomainModelConfiguration {
            get {
                return ResourceManager.GetString("Exception_InvalidDomainModelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no valid next page metadata available.
        /// </summary>
        internal static string Exception_InvalidNextPage {
            get {
                return ResourceManager.GetString("Exception_InvalidNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queryable source does not support async.
        /// </summary>
        internal static string Exception_InvalidOperation_NotAsyncQueryableSource {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NotAsyncQueryableSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size has to be equal or greater than 1.
        /// </summary>
        internal static string Exception_InvalidPageSize {
            get {
                return ResourceManager.GetString("Exception_InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not a resource from the SharePoint site {1}.
        /// </summary>
        internal static string Exception_InvalidSPOResource {
            get {
                return ResourceManager.GetString("Exception_InvalidSPOResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected TResult of type {0} or {1}.
        /// </summary>
        internal static string Exception_InvalidTResultType {
            get {
                return ResourceManager.GetString("Exception_InvalidTResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for object to add to the collection.
        /// </summary>
        internal static string Exception_InvalidTypeForCollection {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for the filter object.
        /// </summary>
        internal static string Exception_InvalidTypeForFilter {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeForFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested index is out of the JSON array boundaries.
        /// </summary>
        internal static string Exception_Json_ArrayOutOfBoundaries {
            get {
                return ResourceManager.GetString("Exception_Json_ArrayOutOfBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected JSON array is empty.
        /// </summary>
        internal static string Exception_Json_EmptyArray {
            get {
                return ResourceManager.GetString("Exception_Json_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for {0} in {1}.
        /// </summary>
        internal static string Exception_LinqError_MissingValue {
            get {
                return ResourceManager.GetString("Exception_LinqError_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding requires the implementation of an AddApiCallHandler handler returning an add ApiCall.
        /// </summary>
        internal static string Exception_MissingAddApiHandler {
            get {
                return ResourceManager.GetString("Exception_MissingAddApiHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each domain model object must be decorated with a ClassMapping attribute.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingClassMapping {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingClassMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the GraphGet/GraphGetLinq field of the ClassMapping property.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingGetMapping {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingGetMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphName was not set.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingGraphName {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model entity does not have a SharePointLinqGet or GraphLinqGet value set.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingLinqGet {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingLinqGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving property could not be determined, most likely the internal implemenation is not aligned with the interface naming.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_ModelOutOfSync {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_ModelOutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not exist in this entity.
        /// </summary>
        internal static string Exception_PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("Exception_PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} was not yet loaded.
        /// </summary>
        internal static string Exception_PropertyNotLoaded {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first fetch this list from SharePoint before doing operations on it.
        /// </summary>
        internal static string Exception_PropertyNotLoaded_List {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &apos;Include&apos; method is supported.
        /// </summary>
        internal static string Exception_PropertyNotLoaded_OnlyIncludeSupported {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded_OnlyIncludeSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests inside a batch reached their max retry count of {0}.
        /// </summary>
        internal static string Exception_ServiceException_BatchMaxRetries {
            get {
                return ResourceManager.GetString("Exception_ServiceException_BatchMaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request reached it&apos;s max retry count of {0}.
        /// </summary>
        internal static string Exception_ServiceException_MaxRetries {
            get {
                return ResourceManager.GetString("Exception_ServiceException_MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected HTTP result value in returned batch response.
        /// </summary>
        internal static string Exception_SharePointRest_UnexpectedResult {
            get {
                return ResourceManager.GetString("Exception_SharePointRest_UnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retries of {0} reached while waiting for Teams operation {1}.
        /// </summary>
        internal static string Exception_TeamsAsyncOperationError_MaxRetries {
            get {
                return ResourceManager.GetString("Exception_TeamsAsyncOperationError_MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}] is missing properties file {1}.
        /// </summary>
        internal static string Exception_Test_MissingPropertiesFile {
            get {
                return ResourceManager.GetString("Exception_Test_MissingPropertiesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}] is missing response file {1}. Request key was {2}.
        /// </summary>
        internal static string Exception_Test_MissingResponseFile {
            get {
                return ResourceManager.GetString("Exception_Test_MissingResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} is expected to be an array but is of type {0} instead.
        /// </summary>
        internal static string Exception_UnexpectedMappingType_NotArray {
            get {
                return ResourceManager.GetString("Exception_UnexpectedMappingType_NotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved tokens found in API call {0}.
        /// </summary>
        internal static string Exception_UnresolvedTokens {
            get {
                return ResourceManager.GetString("Exception_UnresolvedTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new content types on a list is not possible, use the AddAvailableContentType method to add an existing site content type.
        /// </summary>
        internal static string Exception_Unsupported_AddingContentTypeToList {
            get {
                return ResourceManager.GetString("Exception_Unsupported_AddingContentTypeToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Criteria {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not valid.
        /// </summary>
        internal static string Exception_Unsupported_Expression {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionBody {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant {0} is of a non supported type ({1}).
        /// </summary>
        internal static string Exception_Unsupported_ExpressionConstantNotValid {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionConstantNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant {0} is invalid. Only {1} and {2} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionConstantOnlyTypes {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionConstantOnlyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not valid because it must return a boolean result.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionMustReturnBoolean {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionMustReturnBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported. Only calls to {1} indexer are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyIndexer {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is invalid. Only calls to members {1} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyMembers {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is invalid. Only calls to methods {1} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyMethods {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported. Only {1} and {2} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyTypes {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the {0} property requires an extra GET request ({1}) which is not supported when using nested LoadProperties methods.
        /// </summary>
        internal static string Exception_Unsupported_ExtraGet {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExtraGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a relationship can only be done starting from a term.
        /// </summary>
        internal static string Exception_Unsupported_FailedAddingTermRelation {
            get {
                return ResourceManager.GetString("Exception_Unsupported_FailedAddingTermRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsGraphUserAsync on a SharePoint user with principal type different than User or SecurityGroup.
        /// </summary>
        internal static string Exception_Unsupported_GraphUserOnSharePoint {
            get {
                return ResourceManager.GetString("Exception_Unsupported_GraphUserOnSharePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsGraphUserAsync on a SharePoint user without the GraphId property requested and populated.
        /// </summary>
        internal static string Exception_Unsupported_GraphUserOnSharePointNoGraphId {
            get {
                return ResourceManager.GetString("Exception_Unsupported_GraphUserOnSharePointNoGraphId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive requests cannot be grouped together, execute them one by one.
        /// </summary>
        internal static string Exception_Unsupported_InteractiveRequestBatch {
            get {
                return ResourceManager.GetString("Exception_Unsupported_InteractiveRequestBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of type {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_MemberType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Method {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node of type {0} of expression {1} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_NodeType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The projection is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Projection {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsSharePointUserAsync on a Graph user without the UserPrincipalProperty requested and populated.
        /// </summary>
        internal static string Exception_Unsupported_SharePointUserOnGraph {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SharePointUserOnGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot do a batch add of a model to a modelcollection that was not yet requested. Common reasons are adding an item and using that same item in a single batch.
        /// </summary>
        internal static string Exception_Unsupported_ViaBatch {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ViaBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in Xml String. Chr {0} is illegal.
        /// </summary>
        internal static string Exception_Xml_InvalidXmlCharacter {
            get {
                return ResourceManager.GetString("Exception_Xml_InvalidXmlCharacter", resourceCulture);
            }
        }
    }
}
