//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PnPCoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PnPCoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.PnPCoreResources", typeof(PnPCoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expression is not valid.
        /// </summary>
        internal static string Exception_ArgumentExpressionNotValid {
            get {
                return ResourceManager.GetString("Exception_ArgumentExpressionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retries of {0} reached while waiting for operation {1}.
        /// </summary>
        internal static string Exception_AsyncOperationError_MaxRetries {
            get {
                return ResourceManager.GetString("Exception_AsyncOperationError_MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batchrequest {0} was not found in one of the current batches.
        /// </summary>
        internal static string Exception_BatchClient_BatchRequestIdNotFound {
            get {
                return ResourceManager.GetString("Exception_BatchClient_BatchRequestIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the result since batch was not yet executed.
        /// </summary>
        internal static string Exception_BatchResult_BatchNotYetExecuted {
            get {
                return ResourceManager.GetString("Exception_BatchResult_BatchNotYetExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be 0.
        /// </summary>
        internal static string Exception_CannotBeZero {
            get {
                return ResourceManager.GetString("Exception_CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you load this collection once before calling GetAllPages or GetNextPage.
        /// </summary>
        internal static string Exception_CollectionNotLoaded {
            get {
                return ResourceManager.GetString("Exception_CollectionNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GraphAlwaysUseBeta is set to true, you can&apos;t turn off the &apos;on-demand&apos; beta support. First set GraphAlwaysUseBeta to false before turning of GraphCanUseBeta.
        /// </summary>
        internal static string Exception_ConfigurationError_CannotSetCanUseBeta {
            get {
                return ResourceManager.GetString("Exception_ConfigurationError_CannotSetCanUseBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration name &apos;{0}&apos; for PnPContext creation.
        /// </summary>
        internal static string Exception_ConfigurationError_InvalidPnPContextConfigurationName {
            get {
                return ResourceManager.GetString("Exception_ConfigurationError_InvalidPnPContextConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on obtaining the content type.
        /// </summary>
        internal static string Exception_ContentType_ErrorObtaining {
            get {
                return ResourceManager.GetString("Exception_ContentType_ErrorObtaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified content type is not of type &apos;Document Set&apos;. Impossible to return this as &apos;Document Set&apos;.
        /// </summary>
        internal static string Exception_ContentType_NoDocumentSet {
            get {
                return ResourceManager.GetString("Exception_ContentType_NoDocumentSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified content type is not of type &apos;Document Set&apos;. Start your ID with 0x0120D520.
        /// </summary>
        internal static string Exception_ContentType_WrongDocumentSetId {
            get {
                return ResourceManager.GetString("Exception_ContentType_WrongDocumentSetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no authentication provider setup, please ensure you define an authentication provider via configuration or via code. See https://pnp.github.io/pnpcore/using-the-sdk/readme.html for more details.
        /// </summary>
        internal static string Exception_CreatePnPContext_AuthenticationProvider {
            get {
                return ResourceManager.GetString("Exception_CreatePnPContext_AuthenticationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the id (Guid) of a the Microsoft 365 group you want to create a PnPContext for.
        /// </summary>
        internal static string Exception_CreatePnPContext_GroupId {
            get {
                return ResourceManager.GetString("Exception_CreatePnPContext_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided CSOM datetime ({0}) is malformed.
        /// </summary>
        internal static string Exception_CSOM_MalformedDateTime {
            get {
                return ResourceManager.GetString("Exception_CSOM_MalformedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions for the user could not be found.
        /// </summary>
        internal static string Exception_EffectivePermissionsNotFound {
            get {
                return ResourceManager.GetString("Exception_EffectivePermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature was already activated.
        /// </summary>
        internal static string Exception_Feature_AlreadyActivated {
            get {
                return ResourceManager.GetString("Exception_Feature_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature was not activated, nothing to deactive.
        /// </summary>
        internal static string Exception_Feature_CannotDeactivateNotActive {
            get {
                return ResourceManager.GetString("Exception_Feature_CannotDeactivateNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a value for the ServerRelativeUrl parameter.
        /// </summary>
        internal static string Exception_GetListByServerRelativeUrl_ServerRelativeUrl {
            get {
                return ResourceManager.GetString("Exception_GetListByServerRelativeUrl_ServerRelativeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding this entity requires the use of the Graph beta endpoint.
        /// </summary>
        internal static string Exception_GraphBetaNotAllowed {
            get {
                return ResourceManager.GetString("Exception_GraphBetaNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model instance was deleted, you can&apos;t use it anymore.
        /// </summary>
        internal static string Exception_InstanceWasDeleted {
            get {
                return ResourceManager.GetString("Exception_InstanceWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expiration date is invalid. Should be greater than today and within {0} months.
        /// </summary>
        internal static string Exception_Invalid_WebhookExpiration {
            get {
                return ResourceManager.GetString("Exception_Invalid_WebhookExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments number.
        /// </summary>
        internal static string Exception_InvalidArgumentsNumber {
            get {
                return ResourceManager.GetString("Exception_InvalidArgumentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain model configuration for entity {0}.
        /// </summary>
        internal static string Exception_InvalidDomainModelConfiguration {
            get {
                return ResourceManager.GetString("Exception_InvalidDomainModelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no valid next page metadata available.
        /// </summary>
        internal static string Exception_InvalidNextPage {
            get {
                return ResourceManager.GetString("Exception_InvalidNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queryable source does not support async.
        /// </summary>
        internal static string Exception_InvalidOperation_NotAsyncQueryableSource {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NotAsyncQueryableSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not a resource from the SharePoint site {1}.
        /// </summary>
        internal static string Exception_InvalidSPOResource {
            get {
                return ResourceManager.GetString("Exception_InvalidSPOResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected TResult of type {0} or {1}.
        /// </summary>
        internal static string Exception_InvalidTResultType {
            get {
                return ResourceManager.GetString("Exception_InvalidTResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for object to add to the collection.
        /// </summary>
        internal static string Exception_InvalidTypeForCollection {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for the filter object.
        /// </summary>
        internal static string Exception_InvalidTypeForFilter {
            get {
                return ResourceManager.GetString("Exception_InvalidTypeForFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested index is out of the JSON array boundaries.
        /// </summary>
        internal static string Exception_Json_ArrayOutOfBoundaries {
            get {
                return ResourceManager.GetString("Exception_Json_ArrayOutOfBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected JSON array is empty.
        /// </summary>
        internal static string Exception_Json_EmptyArray {
            get {
                return ResourceManager.GetString("Exception_Json_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected JSON.
        /// </summary>
        internal static string Exception_Json_Unexpected {
            get {
                return ResourceManager.GetString("Exception_Json_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for {0} in {1}.
        /// </summary>
        internal static string Exception_LinqError_MissingValue {
            get {
                return ResourceManager.GetString("Exception_LinqError_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception while writing field {0}. Verify you&apos;re using the correct InternalName value for the field you want to write to..
        /// </summary>
        internal static string Exception_ListItemAdd_WrongInternalFieldName {
            get {
                return ResourceManager.GetString("Exception_ListItemAdd_WrongInternalFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure your list Fields are loaded before getting list data. E.g. await list.LoadAsync(p =&gt; p.Fields.QueryProperties(p =&gt; p.InternalName, p =&gt; p.FieldTypeKind, p =&gt; p.TypeAsString, p =&gt; p.Title)).
        /// </summary>
        internal static string Exception_ListItemUpdate_NoFieldsLoaded {
            get {
                return ResourceManager.GetString("Exception_ListItemUpdate_NoFieldsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate hidden taxonomy multivalue note field.
        /// </summary>
        internal static string Exception_ListItemUpdate_NoTaxonomyNoteField {
            get {
                return ResourceManager.GetString("Exception_ListItemUpdate_NoTaxonomyNoteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one recipient is needed before a mail can be send.
        /// </summary>
        internal static string Exception_MailHandler_NoRecipient {
            get {
                return ResourceManager.GetString("Exception_MailHandler_NoRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding requires the implementation of an AddApiCallHandler handler returning an add ApiCall.
        /// </summary>
        internal static string Exception_MissingAddApiHandler {
            get {
                return ResourceManager.GetString("Exception_MissingAddApiHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each domain model object must be decorated with a ClassMapping attribute.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingClassMapping {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingClassMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no instantiatable ConcreteType defined on the {0} interface.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingConcreteTypeAttribute {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingConcreteTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the GraphGet/GraphGetLinq field of the ClassMapping property.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingGetMapping {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingGetMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphName was not set.
        /// </summary>
        internal static string Exception_ModelMetadataIncorrect_MissingGraphName {
            get {
                return ResourceManager.GetString("Exception_ModelMetadataIncorrect_MissingGraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t promote a home page as news article.
        /// </summary>
        internal static string Exception_Page_CantPromoteHomePageAsNews {
            get {
                return ResourceManager.GetString("Exception_Page_CantPromoteHomePageAsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use a OneColumnFullWidth section in this site template ({0}).
        /// </summary>
        internal static string Exception_Page_CantUseFullWidthSection {
            get {
                return ResourceManager.GetString("Exception_Page_CantUseFullWidthSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed.
        /// </summary>
        internal static string Exception_Page_ControlNotAllowedInFullWidthSection {
            get {
                return ResourceManager.GetString("Exception_Page_ControlNotAllowedInFullWidthSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zoneEmphasis value needs to be between 0 and 3.
        /// </summary>
        internal static string Exception_Page_InvalidZoneEmphasis {
            get {
                return ResourceManager.GetString("Exception_Page_InvalidZoneEmphasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page layout type could not be determined for this page.
        /// </summary>
        internal static string Exception_Page_LayoutUndetermined {
            get {
                return ResourceManager.GetString("Exception_Page_LayoutUndetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You first need to save the page before you check for the &apos;{0}&apos; property.
        /// </summary>
        internal static string Exception_Page_ListItemNotLoaded {
            get {
                return ResourceManager.GetString("Exception_Page_ListItemNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client side components could be returned for this web...should not happen but it did....
        /// </summary>
        internal static string Exception_Page_NoClientSideComponentsRetrieved {
            get {
                return ResourceManager.GetString("Exception_Page_NoClientSideComponentsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic and News Digest pages are not supported for creation, they can be read, copied and deleted but you can&apos;t create new ones.
        /// </summary>
        internal static string Exception_Page_NotSupportedPageTypeForCreate {
            get {
                return ResourceManager.GetString("Exception_Page_NotSupportedPageTypeForCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only promote article and repost pages as news article.
        /// </summary>
        internal static string Exception_Page_PageCannotBePromotedAsNews {
            get {
                return ResourceManager.GetString("Exception_Page_PageCannotBePromotedAsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} was not loaded/saved to SharePoint and therefore can&apos;t be deleted.
        /// </summary>
        internal static string Exception_Page_PageWasNotSaved {
            get {
                return ResourceManager.GetString("Exception_Page_PageWasNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a full width section on this page, you can&apos;t add a section with vertical column.
        /// </summary>
        internal static string Exception_Page_VerticalColumnFullWidthSectionExists {
            get {
                return ResourceManager.GetString("Exception_Page_VerticalColumnFullWidthSectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only have one section with a vertical column on a page.
        /// </summary>
        internal static string Exception_Page_VerticalColumnSectionExists {
            get {
                return ResourceManager.GetString("Exception_Page_VerticalColumnSectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a section with vertical column on this page, you can&apos;t add a full width section.
        /// </summary>
        internal static string Exception_Page_VerticalColumnSectionExistsNoFullWidth {
            get {
                return ResourceManager.GetString("Exception_Page_VerticalColumnSectionExistsNoFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a configuration value via the {0} parameter.
        /// </summary>
        internal static string Exception_PnPContext_EmptyConfiguration {
            get {
                return ResourceManager.GetString("Exception_PnPContext_EmptyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed configuration &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string Exception_PnPContext_InvalidConfiguration {
            get {
                return ResourceManager.GetString("Exception_PnPContext_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not exist in this entity.
        /// </summary>
        internal static string Exception_PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("Exception_PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} was not yet loaded.
        /// </summary>
        internal static string Exception_PropertyNotLoaded {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first fetch this list from SharePoint before doing operations on it.
        /// </summary>
        internal static string Exception_PropertyNotLoaded_List {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading nested properties (e.g. RootFolder.ServerRelativeUrl) is not supported, instead you can use RootFolder.QueryProperties(p =&gt; p.ServerRelativeUrl)..
        /// </summary>
        internal static string Exception_PropertyNotLoaded_NestedProperties {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded_NestedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &apos;QueryProperties&apos; method is supported.
        /// </summary>
        internal static string Exception_PropertyNotLoaded_OnlyQueryPropertiesSupported {
            get {
                return ResourceManager.GetString("Exception_PropertyNotLoaded_OnlyQueryPropertiesSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on retrieving the site id from the content type hub.
        /// </summary>
        internal static string Exception_RetrievingContentTypeHubSiteId {
            get {
                return ResourceManager.GetString("Exception_RetrievingContentTypeHubSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role definition &apos;{0}&apos; not found..
        /// </summary>
        internal static string Exception_RoleDefinition_NotFound {
            get {
                return ResourceManager.GetString("Exception_RoleDefinition_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a mail through the &apos;GraphUser&apos; interface is only valid with the application permission authentication flow.
        /// </summary>
        internal static string Exception_SendMailDelegated {
            get {
                return ResourceManager.GetString("Exception_SendMailDelegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a mail through &apos;Me&apos; is only valid with delegated authentication flow.
        /// </summary>
        internal static string Exception_SendMailMe {
            get {
                return ResourceManager.GetString("Exception_SendMailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests inside a batch reached their max retry count of {0}.
        /// </summary>
        internal static string Exception_ServiceException_BatchMaxRetries {
            get {
                return ResourceManager.GetString("Exception_ServiceException_BatchMaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request reached it&apos;s max retry count of {0}.
        /// </summary>
        internal static string Exception_ServiceException_MaxRetries {
            get {
                return ResourceManager.GetString("Exception_ServiceException_MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected HTTP result value in returned batch response.
        /// </summary>
        internal static string Exception_SharePointRest_UnexpectedResult {
            get {
                return ResourceManager.GetString("Exception_SharePointRest_UnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retries of {0} reached while waiting for Teams operation {1}.
        /// </summary>
        internal static string Exception_TeamsAsyncOperationError_MaxRetries {
            get {
                return ResourceManager.GetString("Exception_TeamsAsyncOperationError_MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}] is missing properties file {1}.
        /// </summary>
        internal static string Exception_Test_MissingPropertiesFile {
            get {
                return ResourceManager.GetString("Exception_Test_MissingPropertiesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}] is missing response file {1}. Request key was {2}.
        /// </summary>
        internal static string Exception_Test_MissingResponseFile {
            get {
                return ResourceManager.GetString("Exception_Test_MissingResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved tokens found in API call {0}.
        /// </summary>
        internal static string Exception_UnresolvedTokens {
            get {
                return ResourceManager.GetString("Exception_UnresolvedTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail option is only supported when using the operation &apos;SpecificMail&apos;.
        /// </summary>
        internal static string Exception_Unsupported_AccessRequest_MailNotSupported {
            get {
                return ResourceManager.GetString("Exception_Unsupported_AccessRequest_MailNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pass a valid mail when using the operation &apos;SpecificMail&apos;.
        /// </summary>
        internal static string Exception_Unsupported_AccessRequest_NoMail {
            get {
                return ResourceManager.GetString("Exception_Unsupported_AccessRequest_NoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add a content type to a list on the Content Type Hub.
        /// </summary>
        internal static string Exception_Unsupported_AddingContentTypesToListOnContentTypeHub {
            get {
                return ResourceManager.GetString("Exception_Unsupported_AddingContentTypesToListOnContentTypeHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new content types on a list is not possible, use the AddAvailableContentType method to add an existing site content type.
        /// </summary>
        internal static string Exception_Unsupported_AddingContentTypeToList {
            get {
                return ResourceManager.GetString("Exception_Unsupported_AddingContentTypeToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only set the background image when the header layout is set to Extended..
        /// </summary>
        internal static string Exception_Unsupported_BackgroundImageHeaderIsNotOfTypeExtended {
            get {
                return ResourceManager.GetString("Exception_Unsupported_BackgroundImageHeaderIsNotOfTypeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the UpdateAndPushChangesBatch methods on ContentTypeHub fields is not supported. If you happen to need push updated fields to lists inside the content type hub then directly connect to the content type hub.
        /// </summary>
        internal static string Exception_Unsupported_BatchFieldUpdateAndPushChangesForContentTypeHub {
            get {
                return ResourceManager.GetString("Exception_Unsupported_BatchFieldUpdateAndPushChangesForContentTypeHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch could not be added to list of batches.
        /// </summary>
        internal static string Exception_Unsupported_CannotAddBatch {
            get {
                return ResourceManager.GetString("Exception_Unsupported_CannotAddBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model in the queried collection does not implement the IQueryableDataModel interface.
        /// </summary>
        internal static string Exception_Unsupported_CollectionModelIsNotQueryable {
            get {
                return ResourceManager.GetString("Exception_Unsupported_CollectionModelIsNotQueryable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Criteria {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not valid.
        /// </summary>
        internal static string Exception_Unsupported_Expression {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionBody {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant {0} is of a non supported type ({1}).
        /// </summary>
        internal static string Exception_Unsupported_ExpressionConstantNotValid {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionConstantNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant {0} is invalid. Only {1} and {2} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionConstantOnlyTypes {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionConstantOnlyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not valid because it must return a boolean result.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionMustReturnBoolean {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionMustReturnBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported. Only calls to {1} indexer are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyIndexer {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is invalid. Only calls to members {1} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyMembers {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is invalid. Only calls to methods {1} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyMethods {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression {0} is not supported. Only {1} and {2} are supported.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionOnlyTypes {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionOnlyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression type {0} is not supported inside filtering expressions.
        /// </summary>
        internal static string Exception_Unsupported_ExpressionType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to convert a file with the extension {0} to {1}. Supported extensions are: {2}..
        /// </summary>
        internal static string Exception_Unsupported_Extension_Converting_File {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Extension_Converting_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the {0} property requires an extra GET request ({1}) which is not supported when using nested QueryProperties methods.
        /// </summary>
        internal static string Exception_Unsupported_ExtraGet {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ExtraGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a relationship can only be done starting from a term.
        /// </summary>
        internal static string Exception_Unsupported_FailedAddingTermRelation {
            get {
                return ResourceManager.GetString("Exception_Unsupported_FailedAddingTermRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you&apos;ve requested the &apos;FileServerRelativeUrl&apos; property before you call UpdateAsync() on a file&apos;s properties.
        /// </summary>
        internal static string Exception_Unsupported_FileServerRelativeUrlNotLoaded {
            get {
                return ResourceManager.GetString("Exception_Unsupported_FileServerRelativeUrlNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Follow request is not supported.
        /// </summary>
        internal static string Exception_Unsupported_FollowRequest {
            get {
                return ResourceManager.GetString("Exception_Unsupported_FollowRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsGraphUserAsync on a SharePoint user with principal type different than User or SecurityGroup.
        /// </summary>
        internal static string Exception_Unsupported_GraphUserOnSharePoint {
            get {
                return ResourceManager.GetString("Exception_Unsupported_GraphUserOnSharePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsGraphUserAsync on a SharePoint user without the GraphId property requested and populated.
        /// </summary>
        internal static string Exception_Unsupported_GraphUserOnSharePointNoGraphId {
            get {
                return ResourceManager.GetString("Exception_Unsupported_GraphUserOnSharePointNoGraphId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive requests cannot be grouped together, execute them one by one.
        /// </summary>
        internal static string Exception_Unsupported_InteractiveRequestBatch {
            get {
                return ResourceManager.GetString("Exception_Unsupported_InteractiveRequestBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of type {0} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_MemberType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Method {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide the user via it&apos;s principal when adding a list item or when updating it via one of the Update() methods. Updating using SystemUpdate() or SystemUpdateOverwriteVersion() do work with just the user id value.
        /// </summary>
        internal static string Exception_Unsupported_MissingSharePointPrincipal {
            get {
                return ResourceManager.GetString("Exception_Unsupported_MissingSharePointPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node of type {0} of expression {1} is not supported.
        /// </summary>
        internal static string Exception_Unsupported_NodeType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The used model ({0}) does not implement IQueryableDataModel.
        /// </summary>
        internal static string Exception_Unsupported_NoIQueryableDataModel {
            get {
                return ResourceManager.GetString("Exception_Unsupported_NoIQueryableDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is not a supported mime type: image/png, image/jpeg, image/gif, image/bmp, image/tiff.
        /// </summary>
        internal static string Exception_Unsupported_NotAnImageMimeType {
            get {
                return ResourceManager.GetString("Exception_Unsupported_NotAnImageMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page publish scheduling only works on the pages library in the root web of a site collection.
        /// </summary>
        internal static string Exception_Unsupported_PagePublishingOnSubWeb {
            get {
                return ResourceManager.GetString("Exception_Unsupported_PagePublishingOnSubWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The projection is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Projection {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function can only be called on the content type hub.
        /// </summary>
        internal static string Exception_Unsupported_PublishingContentTypeOutsideContentTypeHub {
            get {
                return ResourceManager.GetString("Exception_Unsupported_PublishingContentTypeOutsideContentTypeHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function can be called from a LINQ query only.
        /// </summary>
        internal static string Exception_Unsupported_QueryPropertiesUse {
            get {
                return ResourceManager.GetString("Exception_Unsupported_QueryPropertiesUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector type is not supported.
        /// </summary>
        internal static string Exception_Unsupported_Selector {
            get {
                return ResourceManager.GetString("Exception_Unsupported_Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t call AsSharePointUserAsync on a Graph user without the UserPrincipalProperty requested and populated.
        /// </summary>
        internal static string Exception_Unsupported_SharePointUserOnGraph {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SharePointUserOnGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is already registered as a hub site..
        /// </summary>
        internal static string Exception_Unsupported_SiteIsAlreadyHubSite {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SiteIsAlreadyHubSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is already part of a hub site..
        /// </summary>
        internal static string Exception_Unsupported_SiteIsAlreadyPartOfAHubSite {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SiteIsAlreadyPartOfAHubSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is not a hub site..
        /// </summary>
        internal static string Exception_Unsupported_SiteIsNotAHubSite {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SiteIsNotAHubSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip on items&apos;s list is not supported. Please consider the usage of CAML query.
        /// </summary>
        internal static string Exception_Unsupported_SkipOnItems {
            get {
                return ResourceManager.GetString("Exception_Unsupported_SkipOnItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unary operator &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string Exception_Unsupported_UnaryOperator {
            get {
                return ResourceManager.GetString("Exception_Unsupported_UnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot do a batch add of a model to a modelcollection that was not yet requested. Common reasons are adding an item and using that same item in a single batch.
        /// </summary>
        internal static string Exception_Unsupported_ViaBatch {
            get {
                return ResourceManager.GetString("Exception_Unsupported_ViaBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete webs in batch, use the DeleteAsync() or Delete() methods.
        /// </summary>
        internal static string Exception_Unsupported_WebDeleteIsInteractive {
            get {
                return ResourceManager.GetString("Exception_Unsupported_WebDeleteIsInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user principal name can not be empty when obtaining user permissions.
        /// </summary>
        internal static string Exception_UserPrincipalNameEmpty {
            get {
                return ResourceManager.GetString("Exception_UserPrincipalNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Everyone except external users could not be ensured.
        /// </summary>
        internal static string Exception_Web_EveyoneExceptUsersCouldNotBeEnsured {
            get {
                return ResourceManager.GetString("Exception_Web_EveyoneExceptUsersCouldNotBeEnsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site template with the name {0} could not be found.
        /// </summary>
        internal static string Exception_WebTemplate_NotFound {
            get {
                return ResourceManager.GetString("Exception_WebTemplate_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in Xml String. Chr {0} is illegal.
        /// </summary>
        internal static string Exception_Xml_InvalidXmlCharacter {
            get {
                return ResourceManager.GetString("Exception_Xml_InvalidXmlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} could not be mapped when converting from JSON.
        /// </summary>
        internal static string Log_Debug_JsonCannotMapField {
            get {
                return ResourceManager.GetString("Log_Debug_JsonCannotMapField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; | File &apos;{1}&apos; | Line Number: {2}  | Started: {3} | Ended {4} | Elapsed {5} ms.
        /// </summary>
        internal static string Log_Debug_LogMetrics {
            get {
                return ResourceManager.GetString("Log_Debug_LogMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} completed.
        /// </summary>
        internal static string Log_Debug_OperationCompleted {
            get {
                return ResourceManager.GetString("Log_Debug_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API call {0} cancelled: {1}.
        /// </summary>
        internal static string Log_Information_ApiCallCancelled {
            get {
                return ResourceManager.GetString("Log_Information_ApiCallCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes so skipping SystemUpdate.
        /// </summary>
        internal static string Log_Information_NoChangesSkipSystemUpdate {
            get {
                return ResourceManager.GetString("Log_Information_NoChangesSkipSystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} not ready yet. Status = {1}. Waiting for {2} seconds, attempt number {3}.
        /// </summary>
        internal static string Log_Information_OperationNotReady {
            get {
                return ResourceManager.GetString("Log_Information_OperationNotReady", resourceCulture);
            }
        }
    }
}
