//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP.Core.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PnPCoreAuthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PnPCoreAuthResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP.Core.Auth.PnPCoreAuthResources", typeof(PnPCoreAuthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for AspNetCoreAuthenticationProvider.
        /// </summary>
        internal static string AspNetCoreAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("AspNetCoreAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized AspNetCoreAuthenticationProvider.
        /// </summary>
        internal static string AspNetCoreAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("AspNetCoreAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved access token for resource {1} with scopes &apos;{2}&apos; from {0}.
        /// </summary>
        internal static string AuthenticationProvider_LogAccessTokenRetrieval {
            get {
                return ResourceManager.GetString("AuthenticationProvider_LogAccessTokenRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided credential manager entry &apos;{0}&apos; does not exist in the system&apos;s credential manager.
        /// </summary>
        internal static string CredentialManagerAuthenticationProvider_CredentialManagerEntryDoesNotExist {
            get {
                return ResourceManager.GetString("CredentialManagerAuthenticationProvider_CredentialManagerEntryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for CredentialManagerAuthenticationProvider.
        /// </summary>
        internal static string CredentialManagerAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("CredentialManagerAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing value for CredentialManagerName in CredentialManagerAuthenticationProvider configuration.
        /// </summary>
        internal static string CredentialManagerAuthenticationProvider_InvalidCredentialManagerName {
            get {
                return ResourceManager.GetString("CredentialManagerAuthenticationProvider_InvalidCredentialManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized CredentialManagerAuthenticationProvider with credential manager item name {0}.
        /// </summary>
        internal static string CredentialManagerAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("CredentialManagerAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for DeviceCodeAuthenticationProvider.
        /// </summary>
        internal static string DeviceCodeAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("DeviceCodeAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized DeviceCodeAuthenticationProvider.
        /// </summary>
        internal static string DeviceCodeAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("DeviceCodeAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for function DeviceCodeVerification in DeviceCodeAuthenticationProvider.
        /// </summary>
        internal static string DeviceCodeAuthenticationProvider_MissingDeviceCodeVerification {
            get {
                return ResourceManager.GetString("DeviceCodeAuthenticationProvider_MissingDeviceCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing default configuration for Authentication Provider Factory.
        /// </summary>
        internal static string Exception_MissingDefaultAuthenticationProvider {
            get {
                return ResourceManager.GetString("Exception_MissingDefaultAuthenticationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized ExternalAuthenticationProvider.
        /// </summary>
        internal static string ExternalAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("ExternalAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for function AccessTokenProvider in ExternalAuthenticationProvider.
        /// </summary>
        internal static string ExternalAuthenticationProvider_MissingAccessTokenProvider {
            get {
                return ResourceManager.GetString("ExternalAuthenticationProvider_MissingAccessTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for InteractiveAuthenticationProvider.
        /// </summary>
        internal static string InteractiveAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("InteractiveAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized InteractiveAuthenticationProvider.
        /// </summary>
        internal static string InteractiveAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("InteractiveAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ClientId value.
        /// </summary>
        internal static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration name &apos;{0}&apos; for IAuthenticationProvider creation!.
        /// </summary>
        internal static string InvalidConfigurationName {
            get {
                return ResourceManager.GetString("InvalidConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing value for ClientSecret or Certificate in OnBehalfOfAuthenticationProvider configuration.
        /// </summary>
        internal static string OnBehalfOfAuthenticationProvider_InvalidClientSecretOrCertificate {
            get {
                return ResourceManager.GetString("OnBehalfOfAuthenticationProvider_InvalidClientSecretOrCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for OnBehalfOfAuthenticationProvider.
        /// </summary>
        internal static string OnBehalfOfAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("OnBehalfOfAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized OnBehalfOfAuthenticationProvider.
        /// </summary>
        internal static string OnBehalfOfAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("OnBehalfOfAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for function UserTokenProvider in OnBehalfOfAuthenticationProvider.
        /// </summary>
        internal static string OnBehalfOfAuthenticationProvider_MissingUserTokenProvider {
            get {
                return ResourceManager.GetString("OnBehalfOfAuthenticationProvider_MissingUserTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for UsernamePasswordAuthenticationProvider.
        /// </summary>
        internal static string UsernamePasswordAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("UsernamePasswordAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing value for Password in UsernamePasswordAuthenticationProvider configuration.
        /// </summary>
        internal static string UsernamePasswordAuthenticationProvider_InvalidPassword {
            get {
                return ResourceManager.GetString("UsernamePasswordAuthenticationProvider_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing value for Username in UsernamePasswordAuthenticationProvider configuration.
        /// </summary>
        internal static string UsernamePasswordAuthenticationProvider_InvalidUsername {
            get {
                return ResourceManager.GetString("UsernamePasswordAuthenticationProvider_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized UsernamePasswordAuthenticationProvider with username {0}.
        /// </summary>
        internal static string UsernamePasswordAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("UsernamePasswordAuthenticationProvider_LogInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the certificate with thumbprint &apos;{0}&apos; in store &apos;{1}&apos; with store location &apos;{2}&apos; while parsing X509CertificateAuthenticationProvider configuration.
        /// </summary>
        internal static string X509CertificateAuthenticationProvider_InvalidCertificate {
            get {
                return ResourceManager.GetString("X509CertificateAuthenticationProvider_InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing value for certificate Thumbprint or Certificate in X509CertificateAuthenticationProvider configuration.
        /// </summary>
        internal static string X509CertificateAuthenticationProvider_InvalidCertificateOrThumbprint {
            get {
                return ResourceManager.GetString("X509CertificateAuthenticationProvider_InvalidCertificateOrThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration for X509CertificateAuthenticationProvider.
        /// </summary>
        internal static string X509CertificateAuthenticationProvider_InvalidConfiguration {
            get {
                return ResourceManager.GetString("X509CertificateAuthenticationProvider_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized X509CertificateAuthenticationProvider with certificate with thumbprint {0} from store {1} location {2}.
        /// </summary>
        internal static string X509CertificateAuthenticationProvider_LogInit {
            get {
                return ResourceManager.GetString("X509CertificateAuthenticationProvider_LogInit", resourceCulture);
            }
        }
    }
}
