<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="System.Net.Http.Json" Version="10.0.*" />-->
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.*" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.*" />
    <PackageReference Include="PnP.Core.Auth" Version="1.17.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\appsettings.*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>wwwroot\appsettings.json</DependentUpon>
    </Content> 
  </ItemGroup>

</Project>
