name: Cleanup old preview nuget package releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
    
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.repository_owner == 'pnp'
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with: 
        ref: dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: '10.0.x'
    - name: Unlist nightly nuget packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
      run: |
        ./build/unlist-nightly.ps1
