name: Nightly nuget release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    
jobs:
  build:
    if: github.repository_owner == 'pnp'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with: 
        ref: dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: '10.0.x'    
    - name: publish nuget 
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
      run: |
        ./build/publish-nightly.ps1
